FROM node:20-alpine

WORKDIR /app

RUN npm install -g pnpm


COPY package.json pnpm-lock.yaml turbo.json ./
COPY apps/gateway/package.json ./apps/gateway/
COPY packages/config/package.json ./packages/config/
COPY packages/tsconfig/package.json ./packages/tsconfig/

RUN pnpm install --no-frozen-lockfile
COPY . .


CMD ["pnpm", "run", "dev"]